# RRP depth-prediction baseline.
project_name: "rrp_model"
run_name: "rrp_model"
use_wandb: true
seed: 0

epochs: 400
batch_size: 4
eval_batch_size: 4
num_workers: 2
gpu_ids: [0]
lr: 1.0e-3
warmup: false
warmup_epochs: 10

encoder_type: "dptv2"
decoder_type: "rrp"
dptv2_ckpt_path: "checkpoints/depth_anything_v2_vits.pth"

image_log_freq: 500
num_images_log: 4
wandb_log_freq: 1

datasets:
  dataset_type: "s3d"
  map_res: 0.02
  data_folder: "datasets_s3d/Structured3D"
  data_splits: "datasets_s3d/Structured3D/split.yaml"
  val_split: "val"
  rgb_img_size: [640, 480]
  floorplan_img_size: [256, 256]
